import React, { useState, useEffect, useRef } from "react";
import { 
  X, Play, Pause, RotateCcw, ChevronRight, ChevronLeft, 
  ShieldCheck, ShieldAlert, Sparkles, CheckCircle2, AlertTriangle,
  FileSearch, Smartphone, Landmark, Cpu, Layers, Award,
  Download, FileText, Globe, ExternalLink, HelpCircle,
  Volume2, VolumeX, Mic
} from "lucide-react";
import { downloadDemoVideoHtml, downloadDemoScriptMarkdown } from "../utils/downloadDemoAssets";
import { demoSpeech } from "../utils/demoSpeech";

interface InteractiveDemoModalProps {
  isOpen: boolean;
  onClose: () => void;
  onNavigateTab?: (tab: "pay" | "verify" | "dashboard" | "recovery" | "simulator") => void;
}

interface DemoStep {
  id: number;
  time: string;
  badge: string;
  title: string;
  category: string;
  durationSeconds: number;
  narration: string;
  highlightPoints: string[];
  visualMock: "normal_payment" | "lottery_scam" | "receipt_ocr" | "recovery_hub" | "scam_simulator" | "jury_matrix";
  targetTab?: "pay" | "verify" | "dashboard" | "recovery" | "simulator";
}

export const InteractiveDemoModal: React.FC<InteractiveDemoModalProps> = ({
  isOpen,
  onClose,
  onNavigateTab
}) => {
  const [currentStepIdx, setCurrentStepIdx] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);
  const [isVoiceEnabled, setIsVoiceEnabled] = useState(true);
  const [progress, setProgress] = useState(0);

  // Total runtime is structured across 6 chapters totaling 2 minutes 30 seconds (150 seconds)
  const steps: DemoStep[] = [
    {
      id: 1,
      time: "0:00 - 0:25",
      badge: "Part 1: The Problem & Vision",
      title: "Real-Time Pre-Transmit Interception",
      category: "The ₹14B Transaction Dilemma",
      durationSeconds: 25,
      narration:
        "Respected jury, India processes over fourteen billion UPI transactions every single month. But every existing banking security system operates post-transaction—sending an SMS alert only after your money has left the account. By that time, fraudsters have already dispersed stolen funds through multi-layered mule accounts in under five minutes, causing recovery rates to plummet below eight percent. SafeUPI flips this paradigm entirely: we intercept and evaluate risk before the user enters their UPI PIN, stopping cyber fraud at the point of intent.",
      highlightPoints: [
        "14+ Billion monthly UPI transactions across India",
        "Legacy bank alerts trigger post-transaction with <8% recovery",
        "Pre-transmit interception prevents funds from ever leaving the device"
      ],
      visualMock: "normal_payment",
      targetTab: "pay"
    },
    {
      id: 2,
      time: "0:25 - 0:55",
      badge: "Part 2: Pre-Payment Risk Engine",
      title: "High-Risk Lottery Scam Intercepted",
      category: "70/30 Ensemble Machine Learning",
      durationSeconds: 30,
      narration:
        "Watch our risk engine in action. Here, a user attempts to transmit forty-eight thousand rupees to an unverified lottery account on a newly logged-in smartphone at two-thirty in the morning. SafeUPI's seventy-thirty hybrid architecture instantly scores this transaction at ninety-four percent extreme risk. Instead of an obscure technical error code, our Explainable AI breaks down the exact risk factors in clear language: a twenty-times spike in amount, a brand new device, and high-risk lottery keywords, giving the user a conscious and protective hard pause.",
      highlightPoints: [
        "Hybrid Formula: (0.70 × Random Forest ML) + (0.30 × Deterministic Rules)",
        "Explainable AI: Breaks down point weights (+35 Device, +25 Amount Spike)",
        "Zero-tolerance heuristic block on known cyber scam patterns"
      ],
      visualMock: "lottery_scam",
      targetTab: "pay"
    },
    {
      id: 3,
      time: "0:55 - 1:25",
      badge: "Part 3: Receipt & QR Forensics",
      title: "Tampered Proofs & Malicious QR Detection",
      category: "Multimodal Computer Vision & OCR",
      durationSeconds: 30,
      narration:
        "Fraud doesn't happen just online—physical merchants lose millions to forged payment confirmation screens generated by fake Paytm and PhonePe APKs, or malicious QR stickers placed over shop stands. SafeUPI's Forensic Studio utilizes optical character recognition and cryptographic signature checks to verify bank reference UTR checksums, font micro-inconsistencies, and UPI gateway parameters in under eighteen milliseconds, protecting shopkeepers from releasing goods without real bank settlement.",
      highlightPoints: [
        "Camera QR scanner verifies digital signature against NPCI gateway registry",
        "OCR text extraction identifies modified amounts and synthetic timestamp fonts",
        "Protects physical merchants against fake payment APK generator scams"
      ],
      visualMock: "receipt_ocr",
      targetTab: "verify"
    },
    {
      id: 4,
      time: "1:25 - 1:55",
      badge: "Part 4: 1930 Incident Recovery Hub",
      title: "Golden Hour Freeze & Auto-Reporting",
      category: "1930 Cyber Helpline & Bank Chargeback",
      durationSeconds: 30,
      narration:
        "When an incident does take place, speed during the first two golden hours is paramount. SafeUPI’s Incident Recovery Hub auto-compiles an encrypted digital evidence dossier with sender and receiver VPAs, transaction reference numbers, and timestamps. It provides instant one-click dialing to the National 1930 Cyber Fraud Helpline, drafts an automated police complaint letter, and tracks the five-stage bank lien process through to judicial refund.",
      highlightPoints: [
        "One-click direct call linkage to 1930 Cyber Crime Helpline",
        "Automated generation of formal police complaint letters & dossiers",
        "Live 5-stage tracker from initial freeze to bank chargeback settlement"
      ],
      visualMock: "recovery_hub",
      targetTab: "recovery"
    },
    {
      id: 5,
      time: "1:55 - 2:20",
      badge: "Part 5: Interactive Scam Simulator",
      title: "Hands-on Cyber Literacy & Awareness",
      category: "Proactive Citizen Cyber Defense",
      durationSeconds: 25,
      narration:
        "Technology alone cannot win this battle; user literacy is our first line of defense. The SafeUPI Scam Simulator trains vulnerable citizens and first-time digital adopters through interactive, real-life fraud simulations—such as electricity disconnection threats, remote desktop malware downloads, and reverse QR refund traps. Users learn the universal golden rule: scanning a QR code or entering a UPI PIN always deducts money, never receives it.",
      highlightPoints: [
        "Real-life simulated attack vectors with instant pedagogical feedback",
        "Teaches citizens that UPI PIN is strictly for payment deduction",
        "Real-time Cyber Awareness Score benchmarking digital resilience"
      ],
      visualMock: "scam_simulator",
      targetTab: "simulator"
    },
    {
      id: 6,
      time: "2:20 - 2:45",
      badge: "Part 6: SIH Jury Architecture",
      title: "Technical Feasibility & National Scale",
      category: "SDK Integration & Zero-PII Compliance",
      durationSeconds: 25,
      narration:
        "Designed from day one as a lightweight, embeddable SDK, SafeUPI integrates effortlessly into existing banking applications like Google Pay, PhonePe, Paytm, or Regional Rural Bank apps. It operates completely client-side without storing personal identifiable information or UPI PINs, complying strictly with RBI Digital Payment Directives. SafeUPI turns every smartphone into an intelligent financial shield. Thank you, and we welcome your questions.",
      highlightPoints: [
        "Ten-dimensional feature vector evaluated in sub-18 milliseconds",
        "Zero server overhead with privacy-first client-side evaluation",
        "White-label SDK ready for national deployment across UPI ecosystem"
      ],
      visualMock: "jury_matrix",
      targetTab: "pay"
    }
  ];

  const currentStep = steps[currentStepIdx];
  const stepStartTimeRef = useRef<number>(Date.now());

  // Speak voiceover on step change or voice toggle
  useEffect(() => {
    if (!isOpen) {
      demoSpeech.stop();
      return;
    }

    if (isVoiceEnabled && isPlaying) {
      // Play transition chime
      if (currentStep.visualMock === "lottery_scam") {
        demoSpeech.playAlertChime("warning");
      } else {
        demoSpeech.playAlertChime("transition");
      }

      // Speak narration
      demoSpeech.speak(currentStep.narration, () => {
        // Voice finished for this chapter
      });
    } else {
      demoSpeech.stop();
    }

    return () => {
      demoSpeech.stop();
    };
  }, [currentStepIdx, isVoiceEnabled, isPlaying, isOpen]);

  // Handle auto-play progression synchronized with chapter duration
  useEffect(() => {
    if (!isOpen || !isPlaying) return;

    stepStartTimeRef.current = Date.now();
    const durationMs = currentStep.durationSeconds * 1000;

    const interval = setInterval(() => {
      const elapsed = Date.now() - stepStartTimeRef.current;
      const pct = Math.min(100, (elapsed / durationMs) * 100);
      setProgress(pct);

      if (pct >= 100) {
        setCurrentStepIdx((curr) => (curr + 1) % steps.length);
        setProgress(0);
      }
    }, 150);

    return () => clearInterval(interval);
  }, [isOpen, isPlaying, currentStepIdx, currentStep.durationSeconds, steps.length]);

  const handleSelectStep = (idx: number) => {
    demoSpeech.stop();
    setCurrentStepIdx(idx);
    setProgress(0);
    stepStartTimeRef.current = Date.now();
  };

  const handleNext = () => {
    demoSpeech.stop();
    setCurrentStepIdx((curr) => (curr + 1) % steps.length);
    setProgress(0);
    stepStartTimeRef.current = Date.now();
  };

  const handlePrev = () => {
    demoSpeech.stop();
    setCurrentStepIdx((curr) => (curr - 1 + steps.length) % steps.length);
    setProgress(0);
    stepStartTimeRef.current = Date.now();
  };

  const toggleVoice = () => {
    const next = !isVoiceEnabled;
    setIsVoiceEnabled(next);
    demoSpeech.setMuted(!next);
    if (!next) {
      demoSpeech.stop();
    } else {
      demoSpeech.speak(currentStep.narration);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div 
        className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-5xl overflow-hidden shadow-2xl flex flex-col max-h-[92vh]"
        role="dialog"
        aria-modal="true"
      >
        {/* Top Video Player Bar */}
        <div className="bg-slate-950 px-4 sm:px-6 py-3.5 border-b border-slate-800 flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-rose-600 flex items-center justify-center text-white font-black text-sm shadow-md shrink-0">
              <Play className="w-4 h-4 fill-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-extrabold text-white">SafeUPI Live Video Walkthrough</h3>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-500/20 text-rose-300 border border-rose-500/30">
                  Full 2m 45s Pitch with Voice
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                AI narration explaining problem statement, 70/30 AI model, and live capabilities
              </p>
            </div>
          </div>

          <div className="flex items-center gap-1.5 sm:gap-2">
            {/* Voice Audio Toggle */}
            <button
              onClick={toggleVoice}
              className={`px-2.5 py-1.5 rounded-xl font-bold text-xs transition-all flex items-center gap-1.5 cursor-pointer border ${
                isVoiceEnabled
                  ? "bg-rose-950/60 border-rose-500/50 text-rose-300 shadow-2xs"
                  : "bg-slate-800 border-slate-700 text-slate-400"
              }`}
              title={isVoiceEnabled ? "Mute Voiceover Audio" : "Enable Voiceover Audio"}
            >
              {isVoiceEnabled ? (
                <>
                  <Volume2 className="w-3.5 h-3.5 text-rose-400 animate-pulse" />
                  <span>Voice ON</span>
                </>
              ) : (
                <>
                  <VolumeX className="w-3.5 h-3.5 text-slate-400" />
                  <span>Voice Muted</span>
                </>
              )}
            </button>

            {/* Download Offline Demo Video (HTML5) */}
            <button
              onClick={() => downloadDemoVideoHtml()}
              className="px-2.5 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs transition-all flex items-center gap-1 cursor-pointer shadow-xs"
              title="Download standalone offline video walkthrough player"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden md:inline">Download Demo Video</span>
              <span className="md:hidden">Video</span>
            </button>

            {/* Download Full Feature Script (.MD) */}
            <button
              onClick={() => downloadDemoScriptMarkdown()}
              className="px-2.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs transition-all flex items-center gap-1 cursor-pointer border border-slate-700"
              title="Download Full Video Script & Feature Guide Markdown"
            >
              <FileText className="w-3.5 h-3.5 text-amber-400" />
              <span className="hidden md:inline">Download Script</span>
              <span className="md:hidden">Script</span>
            </button>

            {/* Auto Play / Pause Toggle */}
            <button
              onClick={() => {
                const next = !isPlaying;
                setIsPlaying(next);
                if (!next) {
                  demoSpeech.pause();
                } else {
                  demoSpeech.resume();
                }
              }}
              className="px-2.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs transition-colors flex items-center gap-1.5 cursor-pointer"
            >
              {isPlaying ? <Pause className="w-3.5 h-3.5 text-amber-400" /> : <Play className="w-3.5 h-3.5 text-emerald-400" />}
              <span>{isPlaying ? "Pause" : "Play"}</span>
            </button>

            <button
              onClick={() => {
                demoSpeech.stop();
                onClose();
              }}
              className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Video Timeline Scrubber */}
        <div className="w-full bg-slate-800 h-1.5 overflow-hidden">
          <div 
            className="bg-gradient-to-r from-rose-500 via-amber-400 to-emerald-400 h-full transition-all duration-150 ease-linear"
            style={{ 
              width: `${((currentStepIdx * 100) / steps.length) + (progress / steps.length)}%` 
            }}
          />
        </div>

        {/* Timeline Chapter Navigation */}
        <div className="bg-slate-950/60 px-4 py-2 border-b border-slate-800/80 flex items-center gap-1.5 overflow-x-auto text-xs">
          {steps.map((s, idx) => (
            <button
              key={s.id}
              onClick={() => handleSelectStep(idx)}
              className={`px-3 py-1 rounded-xl whitespace-nowrap font-bold text-[11px] transition-all cursor-pointer flex items-center gap-1.5 ${
                idx === currentStepIdx
                  ? "bg-rose-600 text-white shadow-xs"
                  : "bg-slate-800/80 text-slate-400 hover:text-slate-200 hover:bg-slate-800"
              }`}
            >
              <span>{s.id}.</span>
              <span>{s.badge.split(":")[1] || s.badge}</span>
            </button>
          ))}
        </div>

        {/* Video Canvas Body: Left Visual Stage + Right Voiceover & Script */}
        <div className="grid grid-cols-1 lg:grid-cols-12 flex-1 overflow-y-auto">
          {/* Visual Display Stage */}
          <div className="lg:col-span-7 bg-slate-950 p-4 sm:p-6 flex flex-col justify-between border-b lg:border-b-0 lg:border-r border-slate-800">
            {/* Visual Header */}
            <div className="flex items-center justify-between text-xs pb-3">
              <span className="text-slate-400 font-mono text-[11px]">{currentStep.time}</span>
              <span className="px-2.5 py-0.5 rounded-full bg-slate-800 text-slate-300 font-bold text-[10px]">
                {currentStep.category}
              </span>
            </div>

            {/* Dynamic Visual Stage Mockup */}
            <div className="my-auto py-2">
              {currentStep.visualMock === "normal_payment" && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-inner space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                    <span className="text-xs font-bold text-slate-400">SIMULATED INTERCEPTION ENGINE</span>
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/20 text-emerald-400">
                      PRE-TRANSMIT ACTIVE
                    </span>
                  </div>
                  <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-rose-500/20 text-rose-400 flex items-center justify-center font-bold">
                      ₹
                    </div>
                    <div>
                      <div className="text-xs text-slate-400">Recipient VPA</div>
                      <div className="text-sm font-mono font-bold text-white">vendor.groceries@okhdfcbank</div>
                    </div>
                    <div className="ml-auto text-right">
                      <div className="text-xs text-slate-400">Amount</div>
                      <div className="text-sm font-bold text-emerald-400">₹450.00</div>
                    </div>
                  </div>
                  <div className="bg-emerald-950/40 border border-emerald-500/30 rounded-xl p-3 flex items-center gap-3">
                    <ShieldCheck className="w-6 h-6 text-emerald-400 shrink-0" />
                    <div className="text-xs">
                      <div className="font-bold text-emerald-300">Risk Score: 12% (Safe & Verified)</div>
                      <div className="text-slate-400 text-[11px]">Regular merchant, trusted device, normal velocity. Fast-tracked to PIN entry.</div>
                    </div>
                  </div>
                </div>
              )}

              {currentStep.visualMock === "lottery_scam" && (
                <div className="bg-slate-900 border border-rose-900/40 rounded-2xl p-5 shadow-inner space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                    <span className="text-xs font-bold text-rose-400">HIGH-RISK SCAM DETECTED</span>
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-600 text-white animate-pulse">
                      PAYMENT HARD-PAUSED
                    </span>
                  </div>
                  <div className="p-4 rounded-xl bg-slate-950 border border-rose-500/30 flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-rose-600 text-white flex items-center justify-center font-bold">
                      !
                    </div>
                    <div>
                      <div className="text-xs text-slate-400">Suspicious Beneficiary</div>
                      <div className="text-sm font-mono font-bold text-rose-300">lucky_draw_winner99@ybl</div>
                    </div>
                    <div className="ml-auto text-right">
                      <div className="text-xs text-slate-400">Abnormal Amount</div>
                      <div className="text-sm font-bold text-rose-400">₹48,000.00</div>
                    </div>
                  </div>
                  <div className="bg-rose-950/60 border border-rose-600/40 rounded-xl p-3 space-y-1.5">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-rose-300 text-xs flex items-center gap-1.5">
                        <AlertTriangle className="w-4 h-4 text-rose-400" />
                        Risk Score: 94% (Extreme Danger)
                      </span>
                      <span className="text-[10px] bg-rose-900 text-rose-200 px-1.5 py-0.5 rounded font-mono font-bold">+35 Device | +25 Spike</span>
                    </div>
                    <p className="text-[11px] text-slate-300">
                      Unusual 20× spike on a newly enrolled device during midnight hours. Known lottery scam VPA pattern.
                    </p>
                  </div>
                </div>
              )}

              {currentStep.visualMock === "receipt_ocr" && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-inner space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                    <span className="text-xs font-bold text-slate-400">MULTIMODAL RECEIPT FORENSICS</span>
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-amber-500/20 text-amber-300">
                      SYNTHETIC FONT FLAGGED
                    </span>
                  </div>
                  <div className="grid grid-cols-2 gap-3 text-xs">
                    <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                      <span className="text-slate-500 text-[10px] block">Extracted UTR Reference</span>
                      <span className="font-mono font-bold text-white text-xs">329188471902</span>
                      <span className="text-[10px] text-rose-400 block mt-1">Checksum Failed (Invalid Bank Format)</span>
                    </div>
                    <div className="bg-slate-950 p-3 rounded-xl border border-slate-800">
                      <span className="text-slate-500 text-[10px] block">QR Code Destination</span>
                      <span className="font-mono font-bold text-amber-300 text-xs">upi://pay?pa=mule.fraud</span>
                      <span className="text-[10px] text-amber-400 block mt-1">Non-matching Merchant Tag</span>
                    </div>
                  </div>
                  <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-[11px] text-slate-300">
                    <span className="font-bold text-amber-400">Forensic Result: </span>
                    Screenshot generated with spoofed Paytm UI application. Money was not actually transferred to merchant.
                  </div>
                </div>
              )}

              {currentStep.visualMock === "recovery_hub" && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-inner space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                    <span className="text-xs font-bold text-slate-400">INCIDENT RECOVERY TIMELINE</span>
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-500/20 text-blue-300">
                      5-STAGE LIEN PROCESS
                    </span>
                  </div>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2.5 text-xs bg-slate-950 p-2.5 rounded-xl border border-slate-800">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span className="text-slate-300">1. Digital Timestamp & Evidence Dossier Generated</span>
                    </div>
                    <div className="flex items-center gap-2.5 text-xs bg-slate-950 p-2.5 rounded-xl border border-slate-800">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span className="text-slate-300">2. Bank Fraud Desk Contacted (Chargeback Request)</span>
                    </div>
                    <div className="flex items-center gap-2.5 text-xs bg-blue-950/40 p-2.5 rounded-xl border border-blue-500/30">
                      <Sparkles className="w-4 h-4 text-blue-400 shrink-0 animate-spin" />
                      <span className="text-blue-200 font-bold">3. 1930 Cyber Crime Portal Acknowledgment Pending</span>
                    </div>
                  </div>
                </div>
              )}

              {currentStep.visualMock === "scam_simulator" && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-inner space-y-3">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                    <span className="text-xs font-bold text-slate-400">PRACTICE LAB SCENARIO</span>
                    <span className="text-xs font-mono font-bold text-amber-400">Score: 4/5</span>
                  </div>
                  <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 text-xs text-slate-300">
                    <p className="font-bold text-white mb-1">Scenario: "Electricity Power Disconnection Threat"</p>
                    <p className="text-[11px] text-slate-400">Caller asks you to pay ₹10 immediately via a shared APK to prevent tonight's electricity cut.</p>
                  </div>
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="p-2 rounded-lg bg-rose-950/40 border border-rose-600/30 text-rose-300 text-center font-bold">
                      ❌ Trust & Pay ₹10
                    </div>
                    <div className="p-2 rounded-lg bg-emerald-950/40 border border-emerald-500/30 text-emerald-300 text-center font-bold">
                      ✓ Hang up & Call Helpline
                    </div>
                  </div>
                </div>
              )}

              {currentStep.visualMock === "jury_matrix" && (
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-inner space-y-3">
                  <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                    <span className="text-xs font-bold text-indigo-400 flex items-center gap-1.5">
                      <Cpu className="w-4 h-4" />
                      TECHNICAL JURY ENSEMBLE SPECIFICATION
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">Latency: 14.2 ms</span>
                  </div>
                  <div className="grid grid-cols-3 gap-2 text-center text-xs">
                    <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
                      <div className="text-slate-500 text-[10px]">Model</div>
                      <div className="font-bold text-white mt-0.5">Random Forest</div>
                    </div>
                    <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
                      <div className="text-slate-500 text-[10px]">Recall</div>
                      <div className="font-bold text-emerald-400 mt-0.5">99.1%</div>
                    </div>
                    <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800">
                      <div className="text-slate-500 text-[10px]">Privacy</div>
                      <div className="font-bold text-indigo-400 mt-0.5">Client Edge</div>
                    </div>
                  </div>
                  <div className="bg-slate-950 p-2.5 rounded-xl border border-slate-800 text-[11px] text-slate-400 font-mono">
                    Formula: (0.70 × ML_Score) + (0.30 × Heuristic_Rules)
                  </div>
                </div>
              )}
            </div>

            {/* Bottom Step Indicator */}
            <div className="pt-3 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
              <span>Section {currentStep.id} of {steps.length}</span>
              {currentStep.targetTab && onNavigateTab && (
                <button
                  onClick={() => {
                    demoSpeech.stop();
                    onNavigateTab(currentStep.targetTab!);
                    onClose();
                  }}
                  className="text-rose-400 hover:text-rose-300 font-bold flex items-center gap-1 cursor-pointer transition-colors"
                >
                  <span>Open this feature in app</span>
                  <ChevronRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          {/* Right Script & Voiceover Guide */}
          <div className="lg:col-span-5 bg-slate-900 p-5 sm:p-6 flex flex-col justify-between">
            <div className="space-y-4">
              <div>
                <span className="text-xs font-bold text-rose-400 uppercase tracking-wider block">
                  {currentStep.badge}
                </span>
                <h2 className="text-lg sm:text-xl font-extrabold text-white mt-1">
                  {currentStep.title}
                </h2>
              </div>

              {/* Spoken Narration Script */}
              <div className="bg-slate-950/80 border border-slate-800 rounded-2xl p-4">
                <div className="text-[10px] uppercase font-bold text-amber-400 tracking-wider mb-1.5 flex items-center justify-between">
                  <div className="flex items-center gap-1.5">
                    <Mic className="w-3.5 h-3.5" />
                    <span>Live Spoken Narration Voice</span>
                  </div>
                  {isVoiceEnabled && (
                    <span className="text-emerald-400 text-[9px] font-bold flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping" />
                      Speaking
                    </span>
                  )}
                </div>
                <p className="text-xs sm:text-sm text-slate-200 leading-relaxed italic">
                  "{currentStep.narration}"
                </p>
              </div>

              {/* Highlight Bullets */}
              <div className="space-y-2">
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
                  Jury Evaluation Key Takeaways
                </span>
                {currentStep.highlightPoints.map((pt, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-slate-300">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                    <span>{pt}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Video Controls Navigation */}
            <div className="pt-5 border-t border-slate-800 flex items-center justify-between gap-3 mt-4">
              <button
                onClick={handlePrev}
                className="px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs flex items-center gap-1 cursor-pointer transition-colors"
              >
                <ChevronLeft className="w-4 h-4" />
                <span>Previous</span>
              </button>

              <button
                onClick={() => handleSelectStep(0)}
                className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
                title="Replay from start"
              >
                <RotateCcw className="w-4 h-4" />
              </button>

              <button
                onClick={handleNext}
                className="px-4 py-2 rounded-xl bg-gradient-to-r from-rose-600 to-rose-700 hover:from-rose-500 hover:to-rose-600 text-white font-extrabold text-xs flex items-center gap-1 shadow-md cursor-pointer transition-all"
              >
                <span>{currentStepIdx === steps.length - 1 ? "Finish Video" : "Next Chapter"}</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
